const PDFDocument=require('pdfkit');
function riskColor(level){return level==='High'?'#b42318':level==='Medium'?'#b54708':'#027a48'}
function line(doc,x1,y1,x2,y2){doc.moveTo(x1,y1).lineTo(x2,y2).stroke('#d0d5dd')}
function bar(doc,x,y,w,h,pct,label){doc.fontSize(9).fillColor('#475467').text(label,x,y-14);doc.roundedRect(x,y,w,h,3).fill('#eef2f6');doc.roundedRect(x,y,w*Math.max(0,Math.min(1,pct)),h,3).fill('#344054')}
function makeReport(project,analysis,scenario,res){const doc=new PDFDocument({margin:42,size:'A4'});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${project.project_code}_analysis.pdf"`);doc.pipe(res);
 doc.fontSize(20).fillColor('#101828').text('Government Project Intelligence Report');doc.moveDown(.3);doc.fontSize(10).fillColor('#667085').text(`${project.project_code} • Generated ${new Date().toLocaleString('en-IN')}`);doc.moveDown();
 doc.roundedRect(42,105,511,80,8).fill('#f8fafc');doc.fontSize(15).fillColor('#101828').text(project.name,58,120,{width:470});doc.fontSize(10).fillColor('#475467').text(`${project.place}, ${project.state} • ${project.sector} • ${project.ministry}`,58,146,{width:470});doc.fontSize(12).fillColor(riskColor(analysis.risk_level)).text(`${analysis.risk_score}% ${analysis.risk_level} total risk`,58,163);
 doc.y=205;doc.fontSize(14).fillColor('#101828').text('Project details');doc.moveDown(.4);const details=[['Project ID',project.project_code],['Implementing agency',project.implementing_agency],['Contractor',project.contractor_name],['Officer',project.officer_name],['Original cost',`₹${project.original_cost_crore} crore`],['Planned duration',`${project.planned_duration_months} months`],['Manpower',`${project.manpower} personnel`],['Coordinates',`${project.latitude}, ${project.longitude}`]];details.forEach((d,i)=>{const x=i%2?310:52,y=doc.y+Math.floor(i/2)*35;doc.fontSize(8).fillColor('#667085').text(d[0],x,y);doc.fontSize(10).fillColor('#101828').text(String(d[1]),x,y+11,{width:230});});doc.y+=145;
 doc.fontSize(14).fillColor('#101828').text('AI risk analysis');doc.moveDown(.5);const metrics=[['Total risk',`${analysis.risk_score}% (${analysis.risk_level})`],['Cost overrun',`${analysis.cost_overrun_pct}%`],['Extra expenditure',`₹${analysis.extra_expenditure_crore} crore`],['Time overrun',`${analysis.time_overrun_pct}%`],['Delay time',`${analysis.delay_time_months} months`]];metrics.forEach((m,i)=>{const x=i%2?310:52,y=doc.y+Math.floor(i/2)*34;doc.fontSize(8).fillColor('#667085').text(m[0],x,y);doc.fontSize(10).fillColor(i===0?riskColor(analysis.risk_level):'#101828').text(m[1],x,y+11,{width:230});});doc.y+=105;
 doc.fontSize(12).fillColor('#101828').text('Risk exposure');bar(doc,52,doc.y+25,490,12,analysis.risk_score/100,'Total risk');bar(doc,52,doc.y+60,490,12,analysis.cost_overrun_pct/100,'Cost overrun %');bar(doc,52,doc.y+95,490,12,analysis.time_overrun_pct/100,'Time overrun %');doc.y+=125;
 doc.fontSize(12).fillColor('#101828').text('Project location snapshot');doc.moveDown(.4);const mx=52,my=doc.y,mw=490,mh=150;doc.roundedRect(mx,my,mw,mh,8).fill('#f7fafc');line(doc,mx+30,my+mh-30,mx+mw-20,my+mh-30);line(doc,mx+30,my+20,mx+30,my+mh-30);doc.fontSize(8).fillColor('#667085').text('Longitude',mx+mw-60,my+mh-20);doc.save();doc.translate(mx+30,my+mh-30);const px=((Number(project.longitude)+180)/360)*(mw-50);const py=(90-Number(project.latitude))/180*(mh-50);doc.circle(px,py,7).fill(riskColor(analysis.risk_level));doc.restore();doc.fontSize(9).fillColor('#344054').text(`${project.place}, ${project.state}`,mx+45,my+24);doc.fontSize(8).fillColor('#667085').text(`Coordinates: ${project.latitude}, ${project.longitude}`,mx+45,my+40);doc.y=my+mh+15;
 if(scenario){doc.fontSize(14).fillColor('#101828').text('What-If scenario comparison');doc.moveDown(.4);doc.fontSize(10).fillColor('#475467').text(`Manpower: ${scenario.manpower} • Budget: ₹${scenario.original_cost_crore} Cr • Planned time: ${scenario.planned_duration_months} months`);doc.moveDown(.5);doc.fontSize(10).fillColor('#101828').text(`Baseline risk: ${analysis.risk_score}%    Scenario risk: ${scenario.risk_score}%    Change: ${(scenario.risk_score-analysis.risk_score).toFixed(1)} points`);doc.moveDown(.3);doc.fontSize(9).fillColor('#475467').text(`Scenario cost overrun: ${scenario.cost_overrun_pct}% • Extra expenditure: ₹${scenario.extra_expenditure_crore} Cr`);doc.text(`Scenario time overrun: ${scenario.time_overrun_pct}% • Delay time: ${scenario.delay_time_months} months`);bar(doc,52,doc.y+20,490,12,analysis.risk_score/100,'Baseline risk');bar(doc,52,doc.y+45,490,12,scenario.risk_score/100,'Scenario risk');doc.y+=70;}
 doc.fontSize(12).fillColor('#101828').text('Recommended actions');analysis.recommendations.forEach(x=>{doc.fontSize(9).fillColor('#475467').text(`• ${x}`,{width:480});});doc.moveDown();doc.fontSize(7).fillColor('#98a2b3').text('Prototype decision-support output. Predictions should be reviewed by authorized project officials. Training set is a public-data-calibrated 900-row prototype dataset.');doc.end();}
module.exports={makeReport};
