import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const qs = new URLSearchParams(window.location.search);
const preselectedProjectId = qs.get('projectId') || '';
const returnUrl = qs.get('returnUrl') || document.referrer || '';
const emptyMilestone = () => ({ taskName:'', plannedPercent:'', actualPercent:'', status:'Pending', notes:'' });
const emptyExpense = () => ({ description:'', category:'', amount:'', proofUrl:'' });

function App(){
 const [projects,setProjects]=useState([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const [milestones,setMilestones]=useState([emptyMilestone()]); const [expenses,setExpenses]=useState([emptyExpense()]); const [files,setFiles]=useState([]);
 const [form,setForm]=useState({projectId:preselectedProjectId,reportingMonth:new Date().toISOString().slice(0,7),overallStatus:'On Track',completionPercentage:0,previousCompletion:'',plannedSummary:'',completedSummary:'',pendingSummary:'',technicalProgress:'',technologiesUsed:'',prototypeStatus:'',testingSummary:'',achievements:'',challenges:'',supportRequired:'',nextMonthPlan:'',nextMonthTarget:'',amountSpentThisMonth:'',totalSpentToDate:'',remainingBudget:'',fundingRequired:false});
 useEffect(()=>{fetch(`${API}/projects`).then(r=>r.json()).then(setProjects).catch(()=>setMessage('Could not load projects. Start the backend first.'))},[]);
 const update=(e)=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});
 const submit=async(e)=>{e.preventDefault();setLoading(true);setMessage(''); try{const fd=new FormData(); Object.entries(form).forEach(([k,v])=>fd.append(k,v)); fd.append('milestones',JSON.stringify(milestones.filter(x=>x.taskName.trim()))); fd.append('expenses',JSON.stringify(expenses.filter(x=>x.description.trim()))); files.forEach(f=>fd.append('evidenceFiles',f)); fd.append('evidenceCaptions',JSON.stringify(files.map(f=>f.name))); const r=await fetch(`${API}/reports`,{method:'POST',body:fd}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Submission failed'); setMessage(`Report submitted successfully. Report ID: ${data.id}`); alert('Report submitted successfully.'); const target = returnUrl && returnUrl.startsWith('http') ? returnUrl : (preselectedProjectId ? `../../src/frontend/projects/project-view.html?id=${encodeURIComponent(preselectedProjectId)}` : '../../src/frontend/projects/projects.html'); window.location.href = target;}catch(err){setMessage(err.message); alert(err.message);}finally{setLoading(false)}};
 return <main><header><h1>SIH26103 — Monthly Project Report</h1><p>Submit your team's monthly progress, expenditure and evidence.</p></header>
 <form onSubmit={submit}>
 <Section title="1. Project Details"><Field label="Project" required><select name="projectId" value={form.projectId} onChange={update} required><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.psId} — {p.title}</option>)}</select></Field><Field label="Reporting month" required><input type="month" name="reportingMonth" value={form.reportingMonth} onChange={update} required/></Field></Section>
 <Section title="2. Overall Status"><Field label="Overall status"><select name="overallStatus" value={form.overallStatus} onChange={update}><option>On Track</option><option>Slightly Delayed</option><option>Significantly Delayed</option><option>On Hold</option><option>Completed</option></select></Field><Field label="Overall completion %" required><input type="number" min="0" max="100" name="completionPercentage" value={form.completionPercentage} onChange={update} required/></Field><Field label="Previous month's completion %"><input type="number" min="0" max="100" name="previousCompletion" value={form.previousCompletion} onChange={update}/></Field></Section>
 <Section title="3. Work & Technical Progress"><Area name="plannedSummary" label="What was planned this month?" value={form.plannedSummary} onChange={update} required/><Area name="completedSummary" label="What was actually completed?" value={form.completedSummary} onChange={update} required/><Area name="pendingSummary" label="What is pending and why?" value={form.pendingSummary} onChange={update}/><Area name="technicalProgress" label="Technical progress" value={form.technicalProgress} onChange={update}/><Area name="technologiesUsed" label="Technologies/tools used" value={form.technologiesUsed} onChange={update}/><Field label="Prototype status"><input name="prototypeStatus" value={form.prototypeStatus} onChange={update} placeholder="V1 / V2 / Final / Field trial"/></Field></Section>
 <Section title="4. Milestones — Planned vs Achieved">{milestones.map((m,i)=><div className="repeat" key={i}><input placeholder="Task / milestone" value={m.taskName} onChange={e=>patch(setMilestones,milestones,i,'taskName',e.target.value)}/><input type="number" min="0" max="100" placeholder="Planned %" value={m.plannedPercent} onChange={e=>patch(setMilestones,milestones,i,'plannedPercent',e.target.value)}/><input type="number" min="0" max="100" placeholder="Actual %" value={m.actualPercent} onChange={e=>patch(setMilestones,milestones,i,'actualPercent',e.target.value)}/><select value={m.status} onChange={e=>patch(setMilestones,milestones,i,'status',e.target.value)}><option>Pending</option><option>In Progress</option><option>Completed</option><option>Delayed</option></select></div>)}<button type="button" onClick={()=>setMilestones([...milestones,emptyMilestone()])}>+ Add milestone</button></Section>
 <Section title="5. Expenditure"><div className="grid"><Field label="Amount spent this month"><input type="number" min="0" step="0.01" name="amountSpentThisMonth" value={form.amountSpentThisMonth} onChange={update}/></Field><Field label="Total spent to date"><input type="number" min="0" step="0.01" name="totalSpentToDate" value={form.totalSpentToDate} onChange={update}/></Field><Field label="Remaining budget"><input type="number" min="0" step="0.01" name="remainingBudget" value={form.remainingBudget} onChange={update}/></Field></div>{expenses.map((x,i)=><div className="repeat" key={i}><input placeholder="Expense description" value={x.description} onChange={e=>patch(setExpenses,expenses,i,'description',e.target.value)}/><input placeholder="Category" value={x.category} onChange={e=>patch(setExpenses,expenses,i,'category',e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Amount" value={x.amount} onChange={e=>patch(setExpenses,expenses,i,'amount',e.target.value)}/></div>)}<button type="button" onClick={()=>setExpenses([...expenses,emptyExpense()])}>+ Add expense</button><label className="check"><input type="checkbox" name="fundingRequired" checked={form.fundingRequired} onChange={update}/> Funding/support required?</label></Section>
 <Section title="6. Testing, Achievements & Challenges"><Area name="testingSummary" label="Testing and results" value={form.testingSummary} onChange={update}/><Area name="achievements" label="Major achievements this month" value={form.achievements} onChange={update}/><Area name="challenges" label="Challenges / risks faced" value={form.challenges} onChange={update}/><Area name="supportRequired" label="Support required from organizers/institution" value={form.supportRequired} onChange={update}/></Section>
 <Section title="7. Images & Evidence"><p className="hint">Upload up to 10 JPG, PNG or WEBP images, max 5 MB each.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,10))}/>{files.length>0&&<ul>{files.map(f=><li key={f.name}>{f.name}</li>)}</ul>}</Section>
 <Section title="8. Next Month Plan"><Area name="nextMonthPlan" label="Tasks and milestones planned for next month" value={form.nextMonthPlan} onChange={update}/><Field label="Expected completion % next month"><input type="number" min="0" max="100" name="nextMonthTarget" value={form.nextMonthTarget} onChange={update}/></Field></Section>
 <button className="submit" disabled={loading}>{loading?'Submitting…':'Submit Monthly Report'}</button>{message&&<div className="message">{message}</div>}
 </form></main>
}
function patch(setter,arr,i,key,val){const copy=arr.map(x=>({...x}));copy[i][key]=val;setter(copy)}
function Section({title,children}){return <section><h2>{title}</h2>{children}</section>}
function Field({label,children,required}){return <label className="field"><span>{label}{required?' *':''}</span>{children}</label>}
function Area({name,label,value,onChange,required}){return <Field label={label} required={required}><textarea name={name} value={value} onChange={onChange} required={required} rows="4"/></Field>}
createRoot(document.getElementById('root')).render(<App/>);
