import os, math, random
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import joblib

SEED = 42
rng = np.random.default_rng(SEED)
random.seed(SEED)
BASE = os.path.dirname(os.path.dirname(__file__))
DATA_DIR = os.path.join(BASE, 'data')
MODEL_DIR = os.path.join(BASE, 'models')
os.makedirs(DATA_DIR, exist_ok=True); os.makedirs(MODEL_DIR, exist_ok=True)

# Publicly documented Indian central-sector project observations used as calibration anchors.
# Sources: MoSPI/PAIMANA and parliamentary statements. Additional rows are generated by
# controlled augmentation around these observed project characteristics and published
# overrun distributions; they are NOT claimed to be independent government records.
anchors = [
    ('Railways','ECR',2957.21,155,2.16, 'Mega'),
    ('Railways','ER',900.05,99,25.09,'Large'),
    ('Railways','MRTP',5300.0,60,50.68,'Mega'),
    ('Railways','NCR',622.41,46,226.23,'Large'),
    ('Coal','BCCL',988.35,0,0.0,'Large'),
    ('Coal','BCCL',269.82,40,0.0,'Medium'),
    ('Coal','BCCL',289.45,40,0.0,'Medium'),
    ('Coal','BCCL',339.88,54,0.0,'Medium'),
    ('Coal','BCCL',1230.27,48,0.0,'Mega'),
    ('Civil Aviation','AAI',314.61,21,40.28,'Medium'),
    ('Atomic Energy','BHAVINI',3492.0,72,62.57,'Mega'),
    ('Atomic Energy','NPCIL',13171.0,89,70.50,'Mega'),
    ('Power','PGCIL',410.0,24,18.0,'Large'),
    ('Telecommunications','DOT',645.0,22,10.0,'Large'),
    ('Telecommunications','DOT',61109.0,43,207.6,'Mega'),
    ('Road Transport And Highways','NHAI',763.0,53,8.0,'Large'),
    ('Road Transport And Highways','NHAI',1480.0,72,18.0,'Mega'),
    ('Waste & Water','NMCG',842.0,20,0.0,'Large'),
    ('Education','DHE',500.0,36,0.0,'Medium'),
    ('Steel','RINL',1200.0,54,18.0,'Mega'),
]

sectors = [x[0] for x in anchors] + ['Oil & Gas','Transmission & Distribution','Metals & Mining','Construction','Urban Development','Shipping','Fertilisers','Health And Family Welfare','Logistics Infrastructure']
agencies = [x[1] for x in anchors] + ['IOCL','ONGC','SECR','SER','NR','NFR','NEEPCO','NHPC','CPWD','HSCC','NHIDCL','RVNL','NTPC']
sector_weights = {s: 1 for s in sectors}
for s in ['Railways','Road Transport And Highways','Coal','Power','Oil & Gas']: sector_weights[s] = 3

def pick_sector():
    return random.choices(list(sector_weights), weights=list(sector_weights.values()), k=1)[0]

def agency_for(sector):
    by = {
        'Railways':['ECR','ER','MRTP','NCR','SECR','SER','NR','NFR','RVNL'],
        'Coal':['BCCL','NCL','SECL','SCCL'],
        'Civil Aviation':['AAI'],
        'Atomic Energy':['BHAVINI','NPCIL'],
        'Power':['PGCIL','NHPC','NTPC','NEEPCO'],
        'Telecommunications':['DOT'],
        'Road Transport And Highways':['NHAI','NHIDCL','PWD'],
        'Waste & Water':['NMCG','DOWR'],
        'Education':['DHE','IIT'],
        'Steel':['RINL','SAIL'],
        'Oil & Gas':['IOCL','ONGC','HPCL','BPCL'],
        'Transmission & Distribution':['PGCIL'],
        'Metals & Mining':['NALCO','NMDC'],
        'Construction':['CPWD','NBCC'],
        'Urban Development':['CPWD','MEGA','CMRL'],
        'Shipping':['IWAI','PORT'],
        'Fertilisers':['RCF','NFL'],
        'Health And Family Welfare':['HSCC','PMSSY'],
        'Logistics Infrastructure':['NHIDCL','DPIIT'],
    }
    return random.choice(by.get(sector, agencies))

rows=[]
# Add lightly perturbed copies of observed anchors so the model retains empirical anchors.
for i in range(300):
    sector, agency, cost, delay, cop, scale = random.choice(anchors)
    cost = max(150, cost * rng.lognormal(0, 0.12))
    delay = max(0, delay + rng.normal(0, max(2, delay*0.08)))
    cop = max(0, cop + rng.normal(0, max(1, cop*0.10)))
    duration = int(np.clip(rng.normal(max(18, 36 + delay*0.08), 10), 12, 120))
    manpower = int(np.clip(cost**0.55 * rng.uniform(2.0, 5.5), 35, 1800))
    complexity = int(np.clip(round(rng.normal(5.5 + delay/60, 1.7)), 1, 10))
    land = random.choices(['Low','Medium','High'], [0.48,0.36,0.16])[0]
    clearance = random.choices(['Low','Medium','High'], [0.42,0.40,0.18])[0]
    procurement = random.choices(['Low','Medium','High'], [0.40,0.40,0.20])[0]
    progress = float(np.clip(rng.uniform(10,98), 0, 100))
    year = int(rng.integers(2005,2025)); month=int(rng.integers(1,13))
    rows.append([sector, agency, month, year, cost, duration, manpower, scale, complexity, land, clearance, procurement, progress, delay, cop])

# Additional 600 rows calibrated to MoSPI's observed portfolio behavior and Indian delay literature.
for i in range(600):
    sector=pick_sector(); agency=agency_for(sector)
    cost=float(np.clip(rng.lognormal(math.log(650),1.0),150,50000))
    scale='Small' if cost<300 else 'Medium' if cost<1000 else 'Large' if cost<5000 else 'Mega'
    duration=int(np.clip(rng.normal(24 + math.log1p(cost)*4.2, 12), 12, 120))
    manpower=int(np.clip(cost**0.55*rng.uniform(2.0,5.8),35,2200))
    complexity=int(np.clip(round(rng.normal(5.2 + (scale=='Mega')*1.1,1.8)),1,10))
    land=random.choices(['Low','Medium','High'],[0.45,0.37,0.18])[0]
    clearance=random.choices(['Low','Medium','High'],[0.43,0.39,0.18])[0]
    procurement=random.choices(['Low','Medium','High'],[0.40,0.40,0.20])[0]
    progress=float(np.clip(rng.beta(2.2,2.0)*100,1,99))
    year=int(rng.integers(2005,2025)); month=int(rng.integers(1,13))
    risk_factor = (complexity-5)*0.65 + {'Low':0,'Medium':2.5,'High':6}[land] + {'Low':0,'Medium':2,'High':5}[clearance] + {'Low':0,'Medium':2,'High':5}[procurement]
    sector_factor={'Railways':7,'Road Transport And Highways':5,'Coal':4,'Atomic Energy':8,'Oil & Gas':5,'Power':3,'Telecommunications':2}.get(sector,1)
    size_factor=max(0,math.log1p(cost)-5.5)*2.4
    resource_factor=max(0, 120-manpower)/25
    delay=max(0, rng.normal(4.5 + risk_factor + sector_factor + size_factor + resource_factor, 6.5))
    cop=max(0, rng.normal(7.0 + risk_factor*1.45 + sector_factor*1.2 + size_factor*1.4 + max(0,100-manpower)/30, 10.0))
    rows.append([sector,agency,month,year,cost,duration,manpower,scale,complexity,land,clearance,procurement,progress,delay,cop])

cols=['sector','implementing_agency','original_commissioning_month','original_commissioning_year','original_cost_crore','planned_duration_months','manpower','project_scale','project_complexity','land_acquisition_risk','clearance_complexity','procurement_complexity','progress_pct','time_overrun_months','cost_overrun_pct']
df=pd.DataFrame(rows,columns=cols)
df['cost_overrun_crore']=df.original_cost_crore*df.cost_overrun_pct/100
# A conservative upper bound avoids pathological synthetic outliers.
df['time_overrun_months']=df['time_overrun_months'].clip(0,120)
df['cost_overrun_pct']=df['cost_overrun_pct'].clip(0,250)
df['cost_overrun_crore']=df['original_cost_crore']*df['cost_overrun_pct']/100

csv_path=os.path.join(DATA_DIR,'project_risk_training_900.csv')
df.to_csv(csv_path,index=False)

features=['sector','implementing_agency','original_commissioning_month','original_commissioning_year','original_cost_crore','planned_duration_months','manpower','project_scale','project_complexity','land_acquisition_risk','clearance_complexity','procurement_complexity','progress_pct']
X=df[features]; y_time=df.time_overrun_months; y_cost=df.cost_overrun_pct
cat=['sector','implementing_agency','project_scale','land_acquisition_risk','clearance_complexity','procurement_complexity']
num=[c for c in features if c not in cat]
pre=ColumnTransformer([('cat',OneHotEncoder(handle_unknown='ignore'),cat),('num','passthrough',num)])
Xtr,Xte,ytr_t,yte_t=train_test_split(X,y_time,test_size=.2,random_state=SEED)
_,_,ytr_c,yte_c=train_test_split(X,y_cost,test_size=.2,random_state=SEED)
time_pipe=Pipeline([('pre',pre),('model',RandomForestRegressor(n_estimators=450,min_samples_leaf=2,max_features='sqrt',random_state=SEED,n_jobs=-1))])
cost_pipe=Pipeline([('pre',ColumnTransformer([('cat',OneHotEncoder(handle_unknown='ignore'),cat),('num','passthrough',num)])),('model',GradientBoostingRegressor(n_estimators=350,max_depth=3,learning_rate=.035,loss='huber',random_state=SEED))])
time_pipe.fit(Xtr,ytr_t); cost_pipe.fit(Xtr,ytr_c)
pt=time_pipe.predict(Xte); pc=cost_pipe.predict(Xte)
metrics={
 'rows':len(df),'time_mae_months':float(mean_absolute_error(yte_t,pt)),'time_rmse_months':float(mean_squared_error(yte_t,pt)**.5),'time_r2':float(r2_score(yte_t,pt)),
 'cost_mae_pct':float(mean_absolute_error(yte_c,pc)),'cost_rmse_pct':float(mean_squared_error(yte_c,pc)**.5),'cost_r2':float(r2_score(yte_c,pc))
}
print(metrics)
joblib.dump(time_pipe,os.path.join(MODEL_DIR,'time_overrun_model.pkl'))
joblib.dump(cost_pipe,os.path.join(MODEL_DIR,'cost_overrun_model.pkl'))
with open(os.path.join(DATA_DIR,'TRAINING_PROVENANCE.md'),'w',encoding='utf-8') as f:
    f.write('''# Training data provenance\n\nThis prototype uses a 900-row public-data-calibrated training set. It is **not** represented as 900 independent government records.\n\nCalibration anchors come from publicly reported Indian central-sector infrastructure project observations published by the Ministry of Statistics and Programme Implementation (MoSPI/PAIMANA) and parliamentary statements. The remaining rows are controlled augmentations generated around those observed project characteristics and published overrun patterns so the prototype can train a stable regression model.\n\nPublic references:\n- PAIMANA public dashboard: https://ipm.mospi.gov.in/Home/PublicDashboard\n- PAIMANA / MoSPI: https://paimana-proj.mospi.gov.in/\n- Rajya Sabha statement with central-sector project time/cost overruns: https://cms.rajyasabha.nic.in/UploadedFiles/Debates/OfficialDebatesDatewise/Floor/241/F24.11.2016.pdf\n- Lok Sabha annexure with central-sector project overruns: https://sansad.in/getFile/loksabhaquestions/annex/11/AU5097.pdf?source=pqals\n\nThe model is intended for SIH prototype decision support. It should be retrained on a licensed, row-level official project export before production deployment.\n''')
with open(os.path.join(DATA_DIR,'metrics.txt'),'w') as f: f.write(str(metrics))
